### ISSUE TITLE
Illegal Character while importing OWASP xml report with maven SonarQube plugin

### ISSUE THREAD

**Issue by limsese** [stevespringett/dependency-check-sonar-plugin#51] opened 2018-02-20 14:33 UTC
Hello, 

I am using Jenkins for continuous Integration and apparently after having upgraded the plugin OWASP dependency Check to last version 3.1.1, I received the following error while importing the xml report generated by the OWASP plugin with the last version of SonarQube plugin 3.4.0.905 (Sonar server: 6.7.1) (Sonar:Dependency-check plugin 1.1.0)

It looks like it fails with characters ? which are present in the generated xml file.

[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar (default-cli) on project omc4-webapp-main: Can not process Dependency-Check report.: Illegal char <?> at index 187: G:\JENKINS\temp\dctempebf761e0-ff68-45f9-941e-5a151e8bf524\check47539468445030423tmp\404\META-INF\resources\webjars\momentjs\2.14.1\package.json?moment

**Comment by stevespringett** [comment] 2018-02-20 15:33
Duplicate of #49

**Closed by stevespringett** 2018-02-20 15:33 UTC
Labels: duplicate

**Comment by limsese** [comment] 2018-02-21 07:49
Oups sorry for the duplicate, I didn't saw the issue #49. Thanks anyway for the fix.
