### ISSUE TITLE
Cannot analyze dependency check report from Jenkins

### ISSUE THREAD

**Issue by fluidjeel** [stevespringett/dependency-check-sonar-plugin#13] opened 2015-12-14 18:39 UTC
I have generated the OWASP dependency check report under WORKSPACE using the Jenkins plugin. But Sonarqube 5.2 isnt analyzing the generated dependency-check-report.xml. Infact I didnt see a sensor phase for OWASP. 

I have declared the following property as well:

<sonar.src>.</sonar.src>
<sonar.dependencyCheck.reportPath>${project.build.directory}/dependency-check-report.xml</sonar.dependencyCheck.reportPath>

The plugin is installed properly, because im able to view the relevant widgets.

The XML plugin is also installed and sonar.import_unknown_files is set as TRUE

**Comment by stevespringett** [comment] 2015-12-14 20:38
Did you specify:

sonar.sources
sonar.dependencyCheck.reportPath

**Comment by stevespringett** [comment] 2015-12-15 18:52
dependency-check-report.xml no longer needs to be part of the paths defined in sonar.sources.

**Comment by fluidjeel** [comment] 2015-12-16 20:00
I have installed the 1.0.3 version of the plugin. But still facing the same issue. I think the sensor ot getting invoked is the issue.

<sonar.src>.</sonar.src>
<sonar.dependencyCheck.reportPath>${project.build.directory}/dependency-check-report.xml</sonar.dependencyCheck.reportPath>

SOnar logs: Clearly shows the plugin is loaded, but sensor is not invoked. Do i need to decalre anything additional in the pom except the report path.

[owasp-debug.txt](https://github.com/stevespringett/dependency-check-sonar-plugin/files/64475/owasp-debug.txt)


Note: the report is available in Jekins ${WORKSPACE}\dependency-check-report.xml

**Comment by stevespringett** [comment] 2015-12-22 18:28
The plugin appears to be downloading, but it's not getting invoked. You should see something like this in your logs:

INFO  - Sensor OWASP Dependency-Check
INFO  - Process Dependency-Check report
INFO  - Process Dependency-Check report (done) | time=977ms
INFO  - Sensor OWASP Dependency-Check (done) | time=979ms

Setting sonar.dependencyCheck.reportPath is all that's required. If the plugin cannot find the report, you'll see this in the logs:

WARN  - Dependency-Check report does not exist. SKIPPING. Please check property sonar.dependencyCheck.reportPath: path/to/dependency-check-report.xml

But I'm not even seeing that, which leads me to believe that Sonar isn't even running the plugin.

**Comment by fluidjeel** [comment] 2015-12-23 18:21
@stevespringett , I have tried re-installing and with different instances of Sonar. The result is the same.

**Comment by stevespringett** [comment] 2015-12-23 18:30
Are you using Sonar Runner, Sonar Jenkins plugin, or Sonar Maven plugin to kick off the job?

**Comment by fluidjeel** [comment] 2015-12-23 18:45
Sonar Jenkins plugin

**Comment by stevespringett** [comment] 2015-12-23 22:11
Using: 
Jenkins 1.609.1
Jenkins SonarQube Plugin 2.3 (configured with SonarQube Runner 2.3 or 2.4)
SonarQube 5.2

I cannot reproduce the issue on a new/default SonarQube install using the embedded database. I typically use the following properties in a SonarQube build step in the Jenkins job config:

sonar.projectKey=my-project-key
sonar.projectName=my-project-name
sonar.projectVersion=1.0.0-SNAPSHOT
sonar.sources=${WORKSPACE}/src
sonar.dependencyCheck.reportPath=target/dependency-check-report.xml

Have you tried the examples?

**Comment by fluidjeel** [comment] 2015-12-24 17:42
I will give it a try soon and then keep you posted.

**Comment by stevespringett** [comment] 2016-04-05 18:36
Closing. If you're still having issues, feel free to reopen or create a new ticket

**Closed by stevespringett** 2016-04-05 18:36 UTC

**Comment by fluidjeel** [comment] 2016-04-05 20:29
sorry for the delay. it worked fine

**Comment by ephemeris-lappis** [comment] 2017-10-05 09:11
Hello.

I'm using Sonar 5.6.5 with OWASP DC plugin 1.0.3. My jobs on Jenkins run dependency check (using maven plugin), and the results are collected on Jenkins. But the Sonar sensor is not launched (no log, no error in console out), and this analysis result are not collected...

Should I configure something on the Sonar side to activate the sensor. Other analysis sensors run as expected : Cobertura, PMD, etc...

Thanks for your help.

Regards.
